name: skillbuddy
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  solana: ^0.31.2+1
  solana_mobile_client: ^0.1.2
  firebase_core: ^3.12.0
  firebase_crashlytics: ^4.3.3
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.3.6
  flutter_secure_storage: ^9.0.0
  flutter_svg: ^2.0.9
  get: ^4.6.6
  internet_connection_checker_plus: ^2.5.2
  google_fonts: ^6.1.0
  is_first_run: ^1.0.0
  package_info_plus: ^8.1.0
  shared_preferences: ^2.2.2
  thor_devkit_dart: ^1.0.1
  url_launcher: ^6.3.0
  flutter_spinkit: ^5.2.0
  gap: ^3.0.1
  chips_choice_null_safety: ^2.0.6
  image_picker: ^1.0.4
  dotted_border: ^2.1.0
  share_plus: ^7.2.2
  path: ^1.8.3
  firebase_analytics: ^11.4.3
  auth_buttons: ^1.0.1+4
  flutter_exif_rotation: ^0.5.2
  flutter_image_compress: ^2.4.0
  google_sign_in: ^6.1.6
  sign_in_with_apple: ^6.1.1
  http: ^1.1.2
  http_parser: ^4.0.0
  material_design_icons_flutter: ^7.0.7296
  extended_image: ^9.0.7

  flutter_launcher_icons: ^0.13.1
  pinput: ^5.0.0
  local_auth: ^2.2.0
  flutter_html: ^3.0.0-beta.2
  intl: ^0.19.0
  mime: ^1.0.6
  rive: ^0.13.15
  flutter_cache_manager: ^3.4.1
  cached_network_image: ^3.4.1
  cached_network_image_platform_interface: ^4.1.1

  file: any
  permission_handler: ^11.3.1
  auto_size_text: ^3.0.0
  firebase_messaging: ^15.2.3
  shimmer: ^3.0.0
  firebase_app_check: ^0.3.2+6
  flutter_branch_sdk: ^8.5.0
  flutter_local_notifications: ^19.2.1
  gradient_progress_bar: ^1.0.7
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter_launcher_icons:
  image_path: "asset/icons/app_icon.png"
  android: "launcher_icon"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "asset/icons/app_icon.png"
  adaptive_icon_scale: 1.2
  ios: true
  remove_alpha_ios: true

flutter:
  assets:
    - asset/
    - asset/locale/
    - asset/images/
    - asset/icons/
    - asset/animations/

  fonts:
    - family: Montserrat
      fonts:
        - asset: asset/fonts/Montserrat-Black.ttf
          weight: 900
        - asset: asset/fonts/Montserrat-ExtraBold.ttf
          weight: 800
        - asset: asset/fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: asset/fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: asset/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: asset/fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: asset/fonts/Montserrat-Thin.ttf
          weight: 300
        - asset: asset/fonts/Montserrat-Light.ttf
          weight: 200
        - asset: asset/fonts/Montserrat-ExtraLight.ttf
          weight: 100
    - family: Poppins
      fonts:
        - asset: asset/fonts/Poppins-Black.ttf
          weight: 900
        - asset: asset/fonts/Poppins-ExtraBold.ttf
          weight: 800
        - asset: asset/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: asset/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: asset/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: asset/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: asset/fonts/Poppins-Thin.ttf
          weight: 300
        - asset: asset/fonts/Poppins-Light.ttf
          weight: 200
        - asset: asset/fonts/Poppins-ExtraLight.ttf
          weight: 100

  uses-material-design: true
