// This file has been automatically generated by Flutter Architect.
//
// Flutter Architect is a tool that generates boilerplate code for your Flutter projects.
// Flutter Architect was created at SayNode Operations AG by Yann Marti, Francesco Romeo and Pedro Gonçalves.
//
// https://saynode.ch

abstract class StorageServiceInterface {
  Future<void> init();

  dynamic readString(String key);
  Future<void> writeString(String key, String value);
  dynamic readInt(String key);
  Future<void> writeInt(String key, int value);
  dynamic readDouble(String key);
  Future<void> writeDouble(String key, double value);
  dynamic readBool(String key);
  // ignore: avoid_positional_boolean_parameters
  Future<void> writeBool(String key, bool value);
  dynamic readStringList(String key);
  Future<void> writeStringList(String key, List<String> value);

  Future<void> delete(String key);
  Future<void> deleteAll();
}
