// This file has been automatically generated by Flutter Architect.
//
// Flutter Architect is a tool that generates boilerplate code for your Flutter projects.
// Flutter Architect was created at SayNode Operations AG by Yann Marti, Francesco Romeo and Pedro Gonçalves.
//
// https://saynode.ch
// ignore_for_file: cascade_invocations
import 'package:get/get.dart';

import '../base/connectivity_base_service.dart';
import '../page/avatar/controllers/avatar_page_controller.dart';
import '../page/create_account_and_login/controller/simple_login_controller.dart';
import '../page/explore_course/controller/discover_courses_controller.dart';
import '../page/leaderboard/controller/leaderboard_controller.dart';
import '../page/my_courses/controller/my_courses_controller.dart';
import '../page/profile/controller/donate_list_controller.dart';
import '../page/profile/controller/profile_controller.dart';
import '../page/token_list/token_list_controller.dart';
import '../service/api_service.dart';
import '../service/auth_service.dart';
import '../service/connectivity_service.dart';
import '../service/logger_service.dart';
import '../service/storage/secure_storage_service.dart';
import '../service/storage/shared_storage_service.dart';
import '../service/storage/storage_service.dart';
import '../widget/popups/controller/donate_controller.dart';
import '../widget/popups/controller/payout_popup_controller.dart';
import 'analytics_service.dart';
import 'branch_service.dart';
import 'content_service.dart';
import 'event_service.dart';
import 'interest_service.dart';
import 'localization_controller.dart';
import 'messaging_service.dart';
import 'reward_claim_and_payout_services.dart';
import 'user_state_service.dart';

class MainBindings extends Bindings {
  @override
  Future<void> dependencies() async {
    //inject services and controllers
    _injectServices();
    _injectControllers();
  }

  void _injectServices() {
    // Services injection:
    Get.lazyPut(UserStateService.new);
    Get.lazyPut(ConnectivityService.new);
    Get.lazyPut(ConnectivityBaseService.new);
    Get.lazyPut(AuthService.new);
    Get.lazyPut(APIService.new);
    Get.lazyPut(StorageService.new);
    Get.lazyPut(SharedStorageService.new);
    Get.lazyPut(SecureStorageService.new);
    Get.lazyPut(LoggerService.new);
    Get.lazyPut(RewardClaimAndPayoutService.new);
    Get.lazyPut(MessagingService.new);
    Get.lazyPut(InterestService.new);
    Get.lazyPut(ContentService.new);
    Get.lazyPut(AnalyticsService.new);
    Get.lazyPut(BranchService.new);
    Get.lazyPut(EventService.new);
  }

  void _injectControllers() {
    // Controllers injection:
    Get.lazyPut(LocalizationController.new, fenix: true);
    Get.lazyPut(DiscoverCoursesController.new, fenix: true);
    Get.lazyPut(MyCoursesController.new, fenix: true);
    Get.lazyPut(LeaderboardController.new, fenix: true);
    Get.lazyPut(ProfileController.new, fenix: true);
    Get.lazyPut(PayoutPopupController.new, fenix: true);
    Get.lazyPut(TokenListController.new, fenix: true);
    Get.lazyPut(SimpleLoginController.new, fenix: true);
    Get.lazyPut(DonateListController.new, fenix: true);
    Get.lazyPut(DonatePopupController.new, fenix: true);
    Get.lazyPut(AvatarPageController.new, fenix: true);
  }
}
