// This file has been automatically generated by Flutter Architect.
//
// Flutter Architect is a tool that generates boilerplate code for your Flutter projects.
// Flutter Architect was created at SayNode Operations AG by Yann Marti, Francesco Romeo and Pedro Gonçalves.
//
// https://saynode.ch

import '../../base/storage/shared_storage_base_service.dart';

class SharedStorageService extends SharedStorageBaseService {
  remove(String last_module_id) {}
}
