// This file has been automatically generated by Flutter Architect.
//
// Flutter Architect is a tool that generates boilerplate code for your Flutter projects.
// Flutter Architect was created at SayNode Operations AG by Yann Marti, Francesco Romeo and Pedro Gonçalves.
//
// https://saynode.ch

import 'package:get/get.dart';
import 'package:internet_connection_checker_plus/internet_connection_checker_plus.dart';

import '../page/lost_connection/lost_connection_page.dart';

class ConnectivityBaseService extends GetxService {
  void init() {
    InternetConnection().onStatusChange.listen((InternetStatus status) {
      switch (status) {
        case InternetStatus.connected:
          // The internet is now connected
          break;
        case InternetStatus.disconnected:
          Get.to<void>(
            () => const LostConnectionPage(),
            transition: Transition.cupertino,
          );
      }
    });

    super.onInit();
  }
}
